name: Conventional Commits

on:
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  commitsar:
    name: Check all commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # la v2 di checkout non funziona
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0

      - name: Run commitsar
        uses: docker://outillage/commitsar:0.11.1
