name: LaTeX workflows

on:
  pull_request:
    branches:
      - master

jobs:
  chktex:
    name: Lint LaTeX files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run chktex
        uses: docker://gruppone/chktex-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
